version: '3.8'

services:
  app:
    build: .
    container_name: projeto-aprendizado
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules # Impede que o volume sobreponha o node_modules do container
